# Generated by Django 4.2.3 on 2023-08-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player',
            new_name='players',
        ),
    ]
